# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: requirements-txt-fixer
    - repo: https://github.com/psf/black
      rev: 21.12b0
      hooks:
          - id: black
            exclude: pynction/version.py
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.931
      hooks:
          - id: mypy
            additional_dependencies: [types-all]
            exclude: ^tests/ ^performance_test.py$
    - repo: https://github.com/PyCQA/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
            additional_dependencies: [flake8-typing-imports==1.12.0]
            exclude: pynction/version.py
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: ["--profile", "black", "--filter-files"]
            name: isort (python)
            exclude: pynction/version.py
