name: continuous_deployment
on:
  push:
    branches:
      - main
jobs:
  coverage:
      runs-on: ubuntu-latest
      name: Send test coverage
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: "3.7"
        - name: Install requirements
          run: pip install -r requirements.txt
        - name: Run tests and collect coverage
          run: |
            coverage run -m pytest tests
            coverage xml
        - name: Upload coverage reports to Codecov with GitHub Action
          uses: codecov/codecov-action@v2
  publish_pypi:
      needs: [coverage]
      runs-on: ubuntu-latest
      name: Publish project to pypi
      steps:
        - uses: actions/checkout@v2
        - name: Set python 3.7
          uses: actions/setup-python@v2
          with:
            python-version: "3.7"
        - name: Build dist
          run: python setup.py sdist
        - name: Publish package on tag creation
          if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.PYPI_API_TOKEN }}
