name: continuous_deployment
on:
  push:
    branches:
      - "main"
jobs:
  publish_pypi:
      runs-on: ubuntu-latest
      name: Publish project to pypi
      steps:
        - uses: actions/checkout@v2
        - uses: relekang/python-semantic-release@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            repository_username: __token__
            repository_password: ${{ secrets.PYPI_API_TOKEN }}
