name: continuous_integration
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "!invoke-release-main-**"
      - "*"
jobs:
  mypy_validation:
    name: MyPy validation 🤖
    uses: ./.github/workflows/python_job.yaml
    with:
      command: mypy .
      python_version: "3.7"
  flake8_validation:
    name: Flake8 validation 💅
    uses: ./.github/workflows/python_job.yaml
    with:
      command: flake8
      python_version: "3.7"
  test:
    name: Python tests 🧪
    needs: [mypy_validation, flake8_validation]
    strategy:
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10"]
    uses: ./.github/workflows/python_job.yaml
    with:
      command: make test
      python_version: ${{ matrix.python_version }}
  send_coverage:
    name: Send test coverage 😎
    needs: [test]
    uses: ./.github/workflows/python_job.yaml
    with:
      command: make coverage-xml
      python_version: "3.7"
      send_coverage: true
