name: continuous_integration
on:
  pull_request:
    branches:
      - "*"
jobs:
  mypy_validation:
    name: MyPy validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run mypy
        run: mypy .
  flake8_validation:
    name: Flake8 validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run flake8
        run: flake8
  test:
    name: test
    runs-on: ubuntu-latest
    needs: [mypy_validation, flake8_validation]
    steps:
      - uses: actions/checkout@v2
      - name: Select python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest tests
