name: send_coverage
on:
  pull_request:
    branches:
      - '!invoke-release-main-**'
      - '*'
  push:
    branches:
      - main
jobs:
  coverage:
      runs-on: ubuntu-latest
      name: Send test coverage
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: "3.7"
        - name: Install requirements
          run: pip install -r requirements.txt
        - name: Run tests and collect coverage
          run: |
            coverage run -m pytest tests
            coverage xml
        - name: Upload coverage reports to Codecov with GitHub Action
          uses: codecov/codecov-action@v2
