name: semantic_versioning
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - '*'
jobs:
  pr_lint:
    name: Ensure semantic PR 🗒️
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            chore
            docs
            ci
          requireScope: false
